c_compiler_version:    # [osx]
- '11'                 # [osx]
cxx_compiler_version:  # [osx]
- '11'                 # [osx]
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "10.12"                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.12"                # [osx and x86_64]
