# texlive doesn't compile with clang=11 due to the use of multiple function definitions
c_compiler_version:    # [osx]
- '12'                 # [osx]
cxx_compiler_version:  # [osx]
- '12'                 # [osx]
