c_compiler_version:    # [osx]
- '11'                 # [osx]
cxx_compiler_version:  # [osx]
- '11'                 # [osx]
macos_machine:         # [osx and 64]
 - x86_64-apple-darwin20.0.0  # [osx and 64]
