{% set name = "vowpalwabbit" %}
{% set version = "9.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/VowpalWabbit/vowpal_wabbit/archive/refs/tags/{{ version }}.tar.gz  
    sha256: e5c8ed20c51900b3cc57650c53753ee12291e061e1d78540c240dc59f7568666
    patches:
      - turn_off_sse2_flags.diff  # [osx and (build_platform != target_platform)]

build:
  number: 3
  skip: true  # [win]
  skip: true  # [python_impl == 'pypy']
  script: 
    - cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON=On -DBUILD_TESTS=Off -DBoost_NO_BOOST_CMAKE=ON -DPY_VERSION=${CONDA_PY:0:1}.${CONDA_PY:1:5} -DBUILD_FLATBUFFERS=ON -DFMT_SYS_DEP=ON -DSPDLOG_SYS_DEP=ON -DRAPIDJSON_SYS_DEP=ON -DCMAKE_INSTALL_LIBDIR=$PREFIX/lib ${CMAKE_ARGS}
    - cmake --build build --parallel --target vw-bin spanning_tree pylibvw
    - python test/run_tests.py --fuzzy_compare
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake >=3.13
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - boost
    - boost-cpp
    - tox
    - zlib
    - fmt
    - rapidjson
    - spdlog
    - flatbuffers
  run:
    - python
    - boost
    - boost-cpp
    - zlib
    - spdlog
    - fmt
    - rapidjson

test:
  imports:
    - vowpalwabbit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/VowpalWabbit/vowpal_wabbit
  summary: Vowpal Wabbit Python package
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jackgerrits
    - gramhagen
    - peterychang
    - xhochy
    - ngam
