{% set name = "vowpalwabbit" %}
{% set version = "9.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/VowpalWabbit/vowpal_wabbit/archive/refs/tags/{{ version }}.tar.gz
  sha256: 9f4ec5cddf67af2c7aa9b380b23fe22c4b11e2109f2cbaa1314bdf3570749a4d
  patches:
    - 0001-Use-system-dependencies.patch
    - 0002-Apply-CMAKE_ARGS-if-set.patch


build:
  number: 0
  skip: true  # [win]
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake >=3.13
    - make
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - libboost-python-devel
    - libboost-devel
    - tox
    - zlib
    - spdlog
    - rapidjson
    - fmt
    - eigen
    - armadillo
    - ensmallen
    - sse2neon  # [arm64 or aarch64 or ppc64le]
  run:
    - python
    - zlib
    - spdlog
    - rapidjson
    - fmt
    - eigen

test:
  source_files:
    - python
    - test
  imports:
    - vowpalwabbit
  commands:
    - pip check
    - python -m pytest python/tests/ -k "not test_ccb_and_automl"  # [python_impl == "cpython" and linux64]
  requires:
    - pip
    - pytest
    - pandas
    - numpy
    - scipy
    - scikit-learn
    - vw-executor  # [linux64]

about:
  home: https://github.com/VowpalWabbit/vowpal_wabbit
  summary: Vowpal Wabbit Python package
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jackgerrits
    - gramhagen
    - xhochy
    - ngam
    - byronxu99
