{% set name = "vowpalwabbit" %}
{% set version = "9.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/VowpalWabbit/vowpal_wabbit/archive/refs/tags/{{ version }}.tar.gz  
    sha256: e5c8ed20c51900b3cc57650c53753ee12291e061e1d78540c240dc59f7568666
    patches:
      - turn_off_sse2_flags.diff  # [osx and (build_platform != target_platform)]
      - 0001-use-sys-deps-add-libs-and-make-install.patch
      - 0002-remove-numbered-version-in-ext_libs.patch
  - url: https://github.com/fmtlib/fmt/archive/835b910.tar.gz
    sha256: e66881ef5089645dbb2105c8b6b7f7eebc6b82b67bc203186c2d67994897dca7
    folder: ext_libs/fmt
  - url: https://github.com/Tencent/rapidjson/archive/f54b0e4.tar.gz
    sha256: 4a76453d36770c9628d7d175a2e9baccbfbd2169ced44f0cb72e86c5f5f2f7cd
    folder: ext_libs/rapidjson
  - url: https://github.com/gabime/spdlog/archive/de0dbfa.tar.gz
    sha256: cdec95055813c8b7cebe9b417bb841ccca95c330d200ac32cc3b3561a305ad38
    folder: ext_libs/spdlog

build:
  number: 4
  skip: true  # [win]
  script: 
     - {{ PYTHON }} -m pip install . -vv
     # these symlink are needed because pypy expects a specific .so
     # upstream hardcodes the .so extension
     # see https://github.com/conda-forge/pypy-meta-feedstock/issues/21
     - EXT_NAME_DIRTY="$(python -m sysconfig | grep "EXT_SUFFIX =")"
     - EXT_NAME_CLEAN=${EXT_NAME_DIRTY:15:200}
     - EXT_NAME=${EXT_NAME_CLEAN%?}
     - ln -s ${SP_DIR}/pylibvw.so ${SP_DIR}/pylibvw${EXT_NAME}  # [python_impl == 'pypy']

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake >=3.13
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - boost
    - boost-cpp
    - tox
    - zlib
    - flatbuffers
    - fmt
    - rapidjson
    - spdlog
  run:
    - python
    - boost
    - boost-cpp
    - zlib
    - flatbuffers
    - fmt
    - rapidjson
    - spdlog

test:
  imports:
    - vowpalwabbit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/VowpalWabbit/vowpal_wabbit
  summary: Vowpal Wabbit Python package
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jackgerrits
    - gramhagen
    - peterychang
    - xhochy
    - ngam
