{% set name = "vowpalwabbit" %}
{% set version = "8.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 37fb7a400f3a7923a04df9921b3eef1bbe96117424ef083dcfed0e4eea77fa08
  patches:
    - remove-sse2-from-flags.patch  # [aarch64 or ppc64le or arm64]

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - cmake >=3.13
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - boost
    - boost-cpp
    - tox
    - zlib
  run:
    - python
    - boost
    - boost-cpp
    - zlib

test:
  imports:
    - vowpalwabbit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/VowpalWabbit/vowpal_wabbit
  summary: Vowpal Wabbit Python package
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gramhagen
    - peterychang
    - xhochy
