# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "i2cKBQnNFVCyjaD9YcT8+F2v1BOhk8IjBqugpFfcFPOWfHUeaZMT68pQPjTFKdq502KyGgpvc+wcBosYajCpzU+GQvpNupLFzdvZ7+/LUi1O53U4KOIYMjn8aiomteXqX1Wp6HW40ZL3a7F6LTMOfW2MKY8SPi8fYMsPmwNkRUvvoBEIidXu0UOK9+m0Y2FOOMCyYZE2wi6XSwXP2E1A+Kzng21DAm0hssBoXRTnm171qNPD/JGU2Y1oZMTZa+Y8Kjanmxs7UMQmPN/cp19BVS6BAxgByMEg8FOy9aOCk/yINjnB692hvtiJPgE8+iI+rQkJTOL8rMOL7S9GdhLzGL/5Pyf81igRoRDtgjrsxFGSxXCsLf1WZBUv3mlyuVSIr3LZwyAtrXLE8RbfjCXMrDX707ezKUl9KYIFQ3RsMo4FoIsaEfkl5MSI2JGAq/6bF4n3S69d5UScbC0vHLyOFU4WfPia1pkVLiVTESO8zwMFkVfWLlxmDgM+/lgsKykF0/7KmoaAhO/ELqU3PYWZIp4efugiQKrH3qMaHrJi1iv2fpEhBD4YZdpjxy4zaqZoaAZNfcpje7ni7dBofGPRwUt66RMFudLleV2jSo+VlJ1oZExE0Jrc5eBk7uo7+CAykpixz/o6PqX9nnlJzAhm6LNcOPrjsX1SG5hfaooorpA="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_python3.6.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_python3.7.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_python3.8.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi